analise_mercado_dados:
  outputs:
    dev:
      account: KDBKQEA-GK51114
      database: JOB_MARKET
      password: '@Guigabia12345'
      role: ACCOUNTADMIN
      schema: GOLD
      threads: 1
      type: snowflake
      user: gyamada22
      warehouse: COMPUTE_WH
  target: dev
dbt_churn:
  outputs:
    dev:
      account: KDBKQEA-GK51114
      database: FINANCE_DB
      password: '@Guigabia12345'
      role: ACCOUNTADMIN
      schema: SILVER
      threads: 1
      type: snowflake
      user: gyamada22
      warehouse: COMPUTE_WH
  target: dev
